#!/bin/sh

start() {
  printf "Loading modules: "
  while read m; do
    modprobe "$m" > /dev/null
  done < /etc/modules
 [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
  printf "Unloading modules: "
  while read m; do
    rmmod "$m" > /dev/null
  done < /etc/modules
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
